#!/bin/bash

set -eu

my_path="$(dirname "$(realpath "$0")")"
# shellcheck source=functions.bash
. "$my_path"/functions.bash

root_mount=$(mktemp -d)
boot_mount=$(mktemp -d)
trap 'rmdir $root_mount $boot_mount' EXIT ERR

show_parts() {
    local dev

    info "Partition layout"
    dev="$1"
    fdisk -l "$dev" || true
    echo >&2
}


show_release() {
    local dev root_part

    dev="$1"
    root_part="$(root_partition "$dev")"
    if [ -e "$root_part" ]; then
        if mount "$root_part" "$root_mount"; then
            if [ -r "$root_mount"/etc/os-release ]; then
                info "Content of /etc/os-release"
                cat "$root_mount"/etc/os-release >&2
                echo >&2
            else
                warning "Cannot find /etc/os-release"
            fi
            umount "$root_mount"
        else
            warning "Cannot mount root partition; bad media?"
        fi
    else
        warning "No root partition; blank media?"
    fi
}


umount_parts() {
    local dev

    dev="$1"
    pattern="$(all_partitions "$dev")"

    info "Waiting for other mounts to show up"
    sleep 3
    while grep -q "$pattern" /proc/mounts; do
        grep -o "$pattern" /proc/mounts | while read -r part; do
            info "Unmounting $part"
            umount "$part"
        done
        sleep 3
    done
}


fix_config() {
    local dev boot_part

    dev="$1"
    boot_part="$(boot_partition "$dev")"
    if [ -e "$boot_part" ]; then
        mount "$boot_part" "$boot_mount"
        if [ -e "$boot_mount"/user-data ]; then
            "$my_path"/customizecard \
                --hostname miss-piggy \
                --username ubuntu \
                --password raspberry \
                --no-expire \
                --kb-model pc105 \
                --kb-layout gb \
                --kb-options ctrl:nocaps \
                --ssh-import-id lp:waveform \
                --apt-cache http://acng.waveform.org.uk:3142 \
                --update --upgrade \
                --install avahi-daemon \
                "$boot_mount"
        fi
        if [ -e "$boot_mount"/config.txt ]; then
            if ! grep "^disable_overscan=1" "$boot_mount"/config.txt >/dev/null; then
                sed -i \
                    -e '/^#disable_overscan/ s/.*/disable_overscan=1/' \
                    "$boot_mount"/config.txt
            fi
        fi
        umount "$boot_mount"
    else
        warning "No boot partition exists after flash!"
        exit 1
    fi
}


usage() {
    echo "Usage: ${0##*/} image-file-or-archive [device]" >&2
}


main() {
    local image dev

    if [ $# -lt 1 ] || [ $# -gt 2 ]; then
        usage
        exit 2
    fi
    case "$1" in
        -h|--help)
            usage
            exit 0
            ;;
        *)
    esac

    if [ $EUID -ne 0 ]; then
        info "Not running as root, re-execing under sudo"
        exec sudo -- "$0" "$@"
    fi

    image=$1
    dev=${2-}

    if [ ! -r "$image" ]; then
        warning "Cannot read $image"
        return 1
    fi

    if [ $# -eq 1 ]; then
        info "Waiting for SD card... "
        dev=$(wait_for_sd)
        echo "Found $dev" >&2
        echo >&2
    else
        echo "Using specified $dev" >&2
    fi

    show_parts "$dev"
    show_release "$dev"

    if confirm "Flash $image to $dev [y/n] "; then
        umount_parts "$dev"
        unpack "$image" | dd of="$dev" bs=16M status=progress
        sync
        show_parts "$dev"
        show_release "$dev"
        fix_config "$dev"
    fi
}


main "$@"
