#!/bin/sh

DEVICE=$(v4l2-ctl --list-devices | awk '
    BEGIN { found=0; }
    /C920/ && !found { found=1; next; }
    found && /\/dev\/video/ { print $0; exit 0; }' -)

if [ -z "$DEVICE" ]; then
    echo "C920 webcam not found" 2>&1
    exit 1

fi

if [ "$#" -ne 1 ]; then
    cat << EOF
$0 mode...

Sets the C920 webcam up for operation in my "challenging" conditions (tons of
backlight, occasionally changing). The "mode" is one (or more) of the following:

day / bright  -- Use lowest gain for bright backgrouns
mid / cloud   -- Use medium gain for midday, or early afternoon
night / dark  -- Use high gain for night or very dark conditions
close / macro -- Set manual focus to close-range
EOF
fi

GAIN=$(v4l2-ctl --get-ctrl=gain | cut -f2 -d" ")
EXPOSURE=$(v4l2-ctl --get-ctrl=exposure_time_absolute | cut -f2 -d" ")
FOCUS=$(v4l2-ctl --get-ctrl=focus_absolute | cut -f2 -d" ")

case "$1" in
    reset)
        v4l2-ctl \
            --set-ctrl=backlight_compensation=0 \
            --set-ctrl=power_line_frequency=1 \
            --set-ctrl=auto_exposure=3 \
            --set-ctrl=gain=0 \
            --set-ctrl=saturation=128 \
            --set-ctrl=focus_automatic_continuous=1 \
            --set-ctrl=exposure_dynamic_framerate=0
        exit 0
        ;;
    bright|day)
        FOCUS=50
        GAIN=16
        EXPOSURE=256
        ;;
    mid|cloudy)
        FOCUS=50
        GAIN=64
        EXPOSURE=256
        ;;
    dark|night)
        FOCUS=50
        GAIN=128
        EXPOSURE=256
        ;;
    close|macro)
        FOCUS=120
        GAIN=128
        EXPOSURE=256
        ;;
    *)
        echo "Unknown setting '$1'" 2>&1
        exit 1
esac

# Compensate for backlight, 50Hz powerline frequency, and bump saturation
v4l2-ctl \
    --set-ctrl=backlight_compensation=1 \
    --set-ctrl=power_line_frequency=1 \
    --set-ctrl=auto_exposure=1 \
    --set-ctrl=gain=$GAIN \
    --set-ctrl=saturation=160 \
    --set-ctrl=focus_automatic_continuous=0 \
    --set-ctrl=exposure_time_absolute=$EXPOSURE
# Focus must be set *after* auto-focus has been disabled
v4l2-ctl --set-ctrl=focus_absolute=$FOCUS
