#!/bin/bash

set -eu


rewrite() {
    local filename script prefix

    script="$1"
    filename="$2"
    if [ -e "$filename" ]; then
        if [ -w "$filename" ]; then
            prefix=
        else
            prefix=sudo
        fi
        $prefix sed -i -E -e "$script" "$filename"
    fi
}

comment() {
    local filename pattern

    pattern="$1"
    filename="$2"
    rewrite "/^ *$pattern/ s/^ */#/" "$filename"
}

uncomment() {
    local filename pattern

    pattern="$1"
    filename="$2"
    rewrite "/^#+ *$pattern/ s/^#+ *//" "$filename"
}

case "${1:-}" in
    -h|--help)
        cat << EOF >& 2
Set your Pi or laptop for away or home environments

usage: setfor <away|home>
EOF
        exit 0
        ;;

    away)
        comment 'leela[^ \t]*:' /etc/fstab
        comment 'Acquire::http' /etc/apt/apt.conf.d/00proxy
        comment 'DEBOOTSTRAP_PROXY' "$HOME"/.mk-sbuild.rc
        for src in $(schroot -l --all-source-chroots); do
            schroot -u root -d / -c $src -- \
                sed -i -E -e '/^ *Acquire/ s/^ */#/' \
                /etc/apt/apt.conf.d/99mk-sbuild-proxy
        done
        if grep -q "Raspberry Pi" /proc/cpuinfo; then
            comment 'dtoverlay=gpio-fan' /boot/firmware/config.txt
            sudo systemctl stop nut-monitor.service || true
            sudo systemctl disable nut-monitor.service || true
        fi
        ;;

    home)
        uncomment 'leela[^ \t]*:' /etc/fstab
        uncomment 'Acquire::http' /etc/apt/apt.conf.d/00proxy
        uncomment 'DEBOOTSTRAP_PROXY' "$HOME"/.mk-sbuild.rc
        for src in $(schroot -l --all-source-chroots); do
            schroot -u root -d / -c $src -- \
                sed -i -E -e '/^#+ *Acquire/ s/^#+ *//' \
                /etc/apt/apt.conf.d/99mk-sbuild-proxy
        done
        if grep -q "Raspberry Pi" /proc/cpuinfo; then
            uncomment 'dtoverlay=gpio-fan' /boot/firmware/config.txt
            sudo systemctl enable nut-monitor.service || true
        fi
        ;;

    *)
        echo "Unrecognized parameter; try --help" >&2
        exit 1
        ;;
esac
