#!/bin/bash

set -eu


rewrite() {
    local filename script prefix

    script="$1"
    filename="$2"
    if [ -e "$filename" ]; then
        if [ -w "$filename" ]; then
            prefix=
        else
            prefix=sudo
        fi
        $prefix sed -i -E -e "$script" "$filename"
    fi
}

comment() {
    local filename pattern

    pattern="$1"
    filename="$2"
    rewrite "/^ *$pattern/ s/^ */#/" "$filename"
}

uncomment() {
    local filename pattern

    pattern="$1"
    filename="$2"
    rewrite "/^#+ *$pattern/ s/^#+ *//" "$filename"
}

case "${1:-}" in
    -h|--help)
        cat << EOF >& 2
Set your Pi or laptop for sprint or home environments

usage: setfor <sprint|home>
EOF
        exit 0
        ;;

    sprint)
        comment 'leela:' /etc/fstab
        comment 'Acquire::http' /etc/apt/apt.conf.d/00proxy
        comment 'dtoverlay=gpio-fan' /boot/firmware/config.txt
        comment 'DEBOOTSTRAP_PROXY' "$HOME"/.mk-sbuild.rc
        if grep -q "Raspberry Pi" /proc/cpuinfo; then
            sudo systemctl enable dot-ip.service
            echo "Replace Fan-shim with Display-o-Tron"
            sudo systemctl disable nut-monitor.service
        fi
        ;;

    home)
        uncomment 'leela:' /etc/fstab
        uncomment 'Acquire::http' /etc/apt/apt.conf.d/00proxy
        uncomment 'dtoverlay=gpio-fan' /boot/firmware/config.txt
        uncomment 'DEBOOTSTRAP_PROXY' "$HOME"/.mk-sbuild.rc
        if grep -q "Raspberry Pi" /proc/cpuinfo; then
            sudo systemctl disable dot-ip.service
            echo "Replace Display-o-Tron with Fan-shim"
            sudo systemctl enable nut-monitor.service
        fi
        ;;

    *)
        echo "Unrecognized parameter; try --help" >&2
        exit 1
        ;;
esac
