#!/usr/bin/python3

import os
import re
import sys
import shutil
import warnings
import datetime as dt
import subprocess as proc
from pathlib import Path
from argparse import Namespace, ArgumentParser
from urllib.parse import unquote, urlsplit
from collections.abc import Callable
from collections import Counter, namedtuple
from typing import Any, Optional, Union, Generator, NamedTuple

from mutagen import mp3, mp4


def defaults() -> Any:
    # This weird setup is just so we can use the handler functions declared
    # later below. The FOLDER_MAP is the important bit. It maps folders under
    # the TARGET path to functions that generate their content. See the
    # function definitions used for more information
    class defaults:
        SOURCE = Path('/mnt/archive/audio')
        TARGET = Path('/media/dave/Media')
        FOLDER_MAP = {
            TARGET / 'Books':           as_is(SOURCE / 'books'),
            TARGET / 'Music By Artist': as_is(SOURCE / 'music'),
            TARGET / 'Music By Album':  by_album(TARGET / 'Music By Artist'),
            #TARGET / 'Music By Genre':  by_genre(TARGET / 'Music By Artist'),
            #TARGET / 'Playlists':       from_playlists(TARGET / '.playlists'),
        }
    return defaults


def main() -> None:
    d = defaults()
    parser = ArgumentParser()
    parser.add_argument(
        '--rsync', default='rsync',
        help="Path to the rsync binary (default: %(default)s)")
    config = parser.parse_args()

    for target, handler in d.FOLDER_MAP.items():
        handler(config, target)
    print('Flushing cache')
    os.sync()


def as_is(source: Path) -> Callable[[Namespace, Path], None]:
    """
    This handler synchronizes the *source* path to the mapped *target* verbatim
    using the configured *rsync* binary. Please note that this includes
    deletion of items under *target* that do not exist in *source*.
    """
    def handler(config: Namespace, target: Path) -> None:
        print(f'Synchronizing {format_path(source)} to '
              f'{format_path(target)}')
        cmd = [
            config.rsync,
            '-rt', # recursive, preserve time-stamps
            '--delete',
            str(source) + '/',
            str(target)
        ]
        proc.run(cmd, check=True, shell=False)
        print(f'Fixing modes under {format_path(target, maxlen=40)}')
        for dirpath, dirnames, filenames, dir_fd in os.fwalk(target):
            for d in dirnames:
                os.chmod(d, 0o775, dir_fd=dir_fd)
            for f in filenames:
                os.chmod(f, 0o664, dir_fd=dir_fd)
    return handler


def by_album(source: Path) -> Callable[[Namespace, Path], None]:
    """
    This handler generates a "by album" view of the specified *source* path,
    under the *target* path it is called with. The *source* is assumed to be
    structured as Artist / Album / Tracks.

    If *source* and *target* are on the same file-system, hardlinks will be
    used to avoid using more space on the device (but ensuring compatibility
    with systems that do not understand symlinks).
    """
    def handler(config: Namespace, target: Path) -> None:
        print(f'Re-generating {format_path(target, maxlen=40)}')
        try:
            shutil.rmtree(target)
        except FileNotFoundError:
            pass
        target.mkdir()
        can_hardlink = same_fs(source, target)
        for artist in source.iterdir():
            if not artist.is_dir():
                continue
            for album in artist.iterdir():
                if not album.is_dir():
                    continue
                try:
                    d = target / album.name
                    d.mkdir()
                except FileExistsError:
                    d = target / f'{album.name} ({artist.name})'
                    d.mkdir()
                for track in album.iterdir():
                    if track.is_file():
                        if can_hardlink:
                            (d / track.name).hardlink_to(track)
                        else:
                            shutil.copy2(track, d / track.name)
    return handler


def by_genre(source: Path, threshold: float=0.5) -> Callable[[Namespace, Path], None]:
    """
    This handler generates a "by genre" view of the specified *source* path,
    under the *target* path it is called with. The *source* is assumed to be
    structured as Artist / Album / Tracks.

    In this case "genre" is calculated at an album level from the genres of all
    tracks in each album. Any genres that appear in at least *threshold* of the
    tracks (50% by default) are assumed to apply to the album as a whole, and
    the album will appear under that genre in the result.

    If *source* and *target* are on the same file-system, hardlinks will be
    used to avoid using more space on the device (but ensuring compatibility
    with systems that do not understand symlinks).
    """
    def handler(config: Namespace, target: Path) -> None:
        print(f'Re-generating {format_path(target, maxlen=40)}')
        try:
            shutil.rmtree(target)
        except FileNotFoundError:
            pass
        target.mkdir()
        can_hardlink = same_fs(source, target)
        for artist in source.iterdir():
            if not artist.is_dir():
                continue
            for album in artist.iterdir():
                if not album.is_dir():
                    continue
                tracks = sum(
                    1
                    for track in album.iterdir()
                    if track.is_file()
                    and track.suffix in ('.mp3', '.mp4', '.m4a')
                )
                genres = Counter(
                    sanitize_filename(genre)
                    for track in album.iterdir()
                    if track.is_file()
                    for genre in (
                        mp3.EasyMP3(str(track)).tags.get('genre', [])
                        if track.suffix == '.mp3' else
                        mp4.MP4(str(track)).tags.get('©gen', [])
                        if track.suffix in ('.m4a', '.mp4') else
                        []
                    )
                )
                for genre, count in genres.items():
                    if count / tracks >= threshold:
                        d = target / genre
                        d.mkdir(exist_ok=True)
                        try:
                            d = (target / genre /
                                 sanitize_filename(album.name))
                            d.mkdir()
                        except FileExistsError:
                            d = (target / genre /
                                 sanitize_filename(f'{album.name} ({artist.name})'))
                            d.mkdir()
                        for track in album.iterdir():
                            if track.is_file():
                                if can_hardlink:
                                    (d / track.name).hardlink_to(track)
                                else:
                                    shutil.copy2(track, d / track.name)
    return handler


class M3UEntry(NamedTuple):
    track:    int = 1
    duration: dt.timedelta = dt.timedelta(seconds=0)
    title:    str = ''
    path:     Path = Path('.')


class M3UPlaylist:
    def __init__(self, path: Union[Path, str]):
        self.path = Path(path)

    def __len__(self) -> int:
        return sum(1 for item in self)

    def __iter__(self) -> Generator[M3UEntry, None, None]:
        with self.path.open('r', encoding='utf-8', errors='ignore') as f:
            lines = f.readlines()
            if lines.pop(0).rstrip() != '#EXTM3U':
                raise ValueError(f'invalid playlist: {self.path}')
            item = M3UEntry()
            info_re = re.compile('^#EXTINF:(?P<duration>\d+),(?P<title>.*)$')
            while lines:
                line = lines.pop(0).rstrip()
                match = info_re.match(line)
                if match:
                    item = item._replace(
                        duration=dt.timedelta(
                            seconds=int(match.group('duration'))),
                        title=match.group('title')
                    )
                else:
                    url = urlsplit(unquote(line))
                    if url.scheme in ('file', ''):
                        yield item._replace(path=Path(url.path))
                    else:
                        warnings.warn(Warning(f'Ignoring non-file URL {line}'))
                    item = M3UEntry(track=item.track + 1)


def from_playlists(source: Path) -> Callable[[Namespace, Path], None]:
    """
    This handler generates a "playlist" view of the specified *source* path,
    under the *target* path it is called with. The *source* is assumed to be
    structured as Artist / Album / Tracks.

    Under the specified *source* path, this handler expects to find one or more
    M3U formatted playlist files. Under the *target* path the handler is called
    with, it will generate folders named after each playlist file found, with
    each track named within.

    If *source* and *target* are on the same file-system, hardlinks will be
    used to avoid using more space on the device (but ensuring compatibility
    with systems that do not understand symlinks).

    .. _M3U: https://en.wikipedia.org/wiki/M3U
    """

    def handler(config: Namespace, target: Path) -> None:
        print(f'Re-generating {format_path(target, maxlen=40)}')
        try:
            shutil.rmtree(target)
        except FileNotFoundError:
            pass
        target.mkdir()
        can_hardlink = same_fs(source, target)
        for path in source.glob('*.m3u'):
            playlist = M3UPlaylist(path)
            d = target / path.name[:-4]
            d.mkdir()
            for entry in playlist:
                name = f'{entry.track:02d}. {entry.title}{entry.path.suffix}'
                name = sanitize_filename(name)
                if can_hardlink:
                    (d / name).hardlink_to(entry.path)
                else:
                    shutil.copy2(entry.path, d / name)
    return handler


def format_path(p: Path, maxlen: int=20) -> str:
    """
    Return the :class:`~pathlib.Path` *p* converted to a :class:`str` for
    display purposes with a maximum length of *maxlen*. Ellipsis will be
    added to denote elided sections.
    """
    result = str(p)
    if len(result) > maxlen:
        result = ''
        for part in reversed(p.parts):
            if len(result) + len(part) + 1 > maxlen:
                break
            result = '/' + part + result
        if result:
            result = '…' + result
        else:
            result = '…' + p.name[-maxlen:]
    return result


_unsafe_re = re.compile(r'[\x00-\x1f\\/:*?"<>|]')
def sanitize_filename(s: str, replace: str='-') -> str:
    """
    Return the :class:`str` *s* with all characters unsafe for a FAT partition
    replaced with *replace*.
    """
    assert not _unsafe_re.match(replace)
    return _unsafe_re.sub(replace, s)


def same_fs(f1: Path, f2: Path) -> bool:
    """
    Return :data:`True` if the paths *f1* and *f2* both belong to the same
    file-system (and thus can be hard-linked if necessary).
    """
    return f1.stat().st_dev == f2.stat().st_dev


if __name__ == '__main__':
    main()
